<?php

	final class QInternationalisation_Iso {
		public function __construct() {}
		
		/**
		 * ISO 3 country code, mapped to respective date format
		 *
		 * @see		https://gist.github.com/mlconnor/1887156
		 *
		 */
		 
		static private $iso3country_date = array(
			'AND' => '',
			'ARE' => 'dd/MM/yyyy',		
			'AFG' => '',		
			'ATG' => '',		
			'AIA' => '',		
			'ALB' => 'yyyy-MM-dd',		
			'ARM' => '',
			'ASM' => '',
			'ATG' => '',
			'ARG' => 'dd/MM/yyyy',
			'AUT' => 'dd.MM.yyyy',
			'AUS' => 'd/MM/yyyy',
			'ABW' => '',		
			'AZE' => '',
			'AGO' => '',
			'ALA' => '',
			'BIH' => 'yyyy-MM-dd',
			'BRB' => '',
			'BGD' => '',
			'BEL' => array(
				'fr'	=>	'd/MM/yyyy',
				'nl'	=>	'd/MM/yyyy',
			),
			
			'BFA' => '',
			'BGR' => 'yyyy-M-d',
			'BHR' => 'dd/MM/yyyy',
			'BDI' => '',		
			'BEN' => '',
			'BMU' => '',
			'BRN' => '',
			'BOL' => '',
			'BRA' => 'dd/MM/yyyy',
			'BHS' => '',
			'BTN' => '',
			'BWA' => '',
			'BLR' => 'd.M.yyyy',
			'BLZ' => '',
			'BLM' => '',
			'BVT' => '',
			'CAN' => array(
				'fr'	=>	'yyyy-MM-dd',
				'en'	=>	'dd/MM/yyyy',
			),
			
			'CCK' => '',
			'CAF' => '',		
			'COG' => '',
			'CHE' => array(
				'de'	=>	'dd.MM.yyyy',
				'fr'	=>	'dd.MM.yyyy',
				'it'	=>	'dd.MM.yyyy',
			),
			
			'CIV' => '',
			'COK' => '',
			'CHL' => 'dd-MM-yyyy',
			'CMR' => '',
			'CHN' => 'yyyy-M-d',
			'COL' => 'd/MM/yyyy',
			'CRI' => 'dd/MM/yyyy',
			'CUB' => '',
			'CPV' => '',
			'CUW' => '',
			'CXR' => '',
			'CYP' => 'dd/MM/yyyy',
			'CZE' => 'd.M.yyyy',
			'COD' => '',
			'DEU' => 'dd.MM.yyyy',
			'DJI' => '',
			'DNK' => 'dd-MM-yyyy',
			'DMA' => '',
			'DOM' => 'MM/dd/yyyy',
			'DZA' => 'dd/MM/yyyy',
			'ECU' => 'dd/MM/yyyy',
			'EST' => 'd.MM.yyyy',
			'EGY' => 'dd/MM/yyyy', 
			'ESH' => '',		
			'ERI' => '',
			'ESP' => array(
				'es'	=>	'd/MM/yyyy',
				'ca'	=>	'dd/MM/yyyy',
			),
			
			'ETH' => '',
			'FIN' => 'd.M.yyyy',
			'FJI' => '',
			'FLK' => '',
			'FRO' => '',
			'FRA' => 'dd/MM/yyyy',
			'FSM' => '',
			'GAB' => '',
			'GBR' => 'dd/MM/yyyy',
			'GRD' => '',
			'GEO' => '',
			'GUF' => '',
			'GIB' => '',
			'GRL' => '',
			'GMB' => '',
			'GNB' => '',
			'GLP' => '',
			'GNQ' => '',		
			'GRC' => 'd/M/yyyy',
			'SGS' => '',		
			'GTM' => 'd/MM/yyyy',
			'GUM' => '',
			'GUY' => '',
			'GGY' => '',
			'GHA' => '',
			'HKG' => 'yyyy年M月d日',
			'HMD' => '',		
			'HRV' => 'dd.MM.yyyy',		
			'HUN' => 'yyyy.MM.dd',
			'HND' => 'MM-dd-yyyy',
			'HTI' => '',
			'IDN' => 'dd/MM/yyyy',
			'ISR' => 'dd/MM/yyyy',
			'IMN' => '',
			'IND' => array(
				'hi'	=>	'',
				'en'	=>	'd/M/yyyy',
			),
			
			'IOT' => '',	
			'IRQ' => 'dd/MM/yyyy',
			'IRN' => '',
			'ISL' => 'd.M.yyyy',
			'ITA' => 'dd/MM/yyyy',
			'IRL' => array(
				'ga' 	=>	'dd/MM/yyyy',
				'en'	=>	'dd/MM/yyyy',
			),
			
			'JAM' => '',
			'JEY' => '',
			'JOR' => 'dd/MM/yyyy',
			'JPN' => 'yyyy/MM/dd',
			'KEN' => '',
			'KGZ' => '',
			'KHM' => '',		
			'KIR' => '',
			'COM' => '',		
			'KNA' => '',		
			'KWT' => 'dd/MM/yyyy',
			'CYM' => '',		
			'KAZ' => '',
			'KOR' => 'yyyy. M. d',
			'LAO' => '',
			'LCA' => '',		
			'LIE' => '',
			'LKA' => '',		
			'LBR' => '',
			'LSO' => '',
			'LTU' => 'yyyy.M.d',
			'LUX' => array(
				'fr'	=>	'dd/MM/yyyy',
				'de'	=>	'dd.MM.yyyy',
			),
			
			'LVA' => 'yyyy.d.M',
			'LBV' => '',
			'LBN' => 'dd/MM/yyyy',
			'LBY' => 'dd/MM/yyyy',
			'MAR' => 'dd/MM/yyyy',
			'MCO' => '',
			'MNE' => 'd.M.yyyy',
			'MAF' => '',		
			'MDG' => '',
			'MHL' => '',
			'MLI' => '',
			'MMR' => '',
			'MNG' => '',
			'MAC' => '',
			'MKD' => 'd.M.yyyy',
			'MNP' => '',		
			'MTQ' => '',
			'MRT' => '',
			'MSR' => '',
			'MLT' => array(
				'en'	=>	'dd/MM/yyyy',
				'mt'	=>	'dd/MM/yyyy',
			),
			
			'MUS' => '',
			'MDV' => '',
			'MWI' => '',
			'MEX' => 'd/MM/yyyy',
			'MYS' => 'dd/MM/yyyy',
			'MOZ' => '',
			'MYT' => '', 
			'NAM' => '',
			'NCL' => '',
			'NER' => '',
			'NFK' => '',
			'NGA' => '',
			'NIC' => 'MM-dd-yyyy',
			'NOR' => 'dd.MM.yyyy',
			'NPL' => '',
			'NRU' => '',
			'NIU' => '',
			'NZL' => 'd/MM/yyyy',
			'NLD' => 'd-M-yyyy',
			'OMN' => 'dd/MM/yyyy',
			'PAN' => 'MM/dd/yyyy',
			'PER' => 'dd/MM/yyyy',
			'PRI' => 'MM-dd-yyyy',
			'PYF' => '',		
			'PNG' => '',
			'PHL' => 'M/d/yyyy',
			'POL' => 'dd.MM.yyyy',
			'PAK' => '',
			'SPM' => '',
			'PCN' => '',
			'PRT' => 'dd-MM-yyyy',
			'PLW' => '',
			'PRY' => 'dd/MM/yyyy',
			'QAT' => 'dd/MM/yyyy',
			'REU' => '',
			'ROU' => 'dd.MM.yyyy',
			'SRB' => 'd.M.yyyy',
			'RUS' => 'dd.MM.yyyy',
			'RWA' => '',
			'SAU' => 'dd/MM/yyyy',
			'SLB' => '',
			'SYC' => '',
			'SDN' => 'dd/MM/yyyy',
			'SWE' => 'yyyy-MM-dd',
			'SGP' => array(
				'zh'	=>	'dd/MM/yyyy',
				'en'	=>	'M/d/yyyy',
			),
			
			'SVN' => 'd.M.yyyy',
			'SJM' => '',
			'SVK' => 'd.M.yyyy',
			'SLE' => '',
			'SMR' => '',
			'SEN' => '',
			'SOM' => '',
			'SUR' => '',
			'SSD' => '',
			'STP' => '',
			'SLV' => 'MM-dd-yyyy',		
			'SYR' => 'dd/MM/yyyy',
			'SWZ' => '',
			'SHN' => '',
			'TCA' => '',
			'TCD' => '',		
			'ATF' => '',		
			'TGO' => '',
			'THA' => 'd/M/2555',
			'TJK' => '',
			'TKL' => '',
			'TLS' => '',
			'TKM' => '',
			'TON' => '',
			'TUR' => 'dd.MM.yyyy',
			'TTO' => '',
			'TUN' => 'dd/MM/yyyy',
			'TUV' => '',
			'TWN' => 'yyyy/M/d',
			'TZA' => '',
			'UKR' => 'dd.MM.yyyy',
			'UGA' => '',
			'UMI' => '',
			'USA' => 'M/d/yyyy',
			'URY' => 'dd/MM/yyyy',
			'UZB' => '',
			'VAT' => '',
			'VCT' => '',	
			'VIR' => '',
			'VNM' => 'dd/MM/yyyy',
			'VUT' => '',
			'VEN' => 'dd/MM/yyyy',
			'WLF' => '',
			'WSM' => '',		
			'YEM' => 'dd/MM/yyyy',
			'MYT' => '',
			'ZAF' => 'yyyy/MM/dd',		
			'ZMB' => '',
			'ZWE' => '',
			'EUR' => ''
			
		);
		
		/**
		 * Return a list of 
		 *
		 *			- ISO 2 country code, and their respective 
		 *			- locale country name
		 *
		 * @param	$code		string
		 *
		 * @return				mixed
		 *
		 */
		 
		static public function countryCodeCountryName( string $code = '' ) { 
			if( empty( $code ) ) {
				return QInternationalisation_Iso::$iso2country_countryname;
			}
			
			return QInternationalisation_Iso::$iso2country_countryname[$code];
		}
		
		/**
		 * ISO 2 country code, mapped to respective name of country
		 *
		 * @see		https://www.localeplanet.com/icu/
		 *
		 */
		 
		static private $iso2country_countryname = array(
			'AE' => 'United Arab Emirates',
			'AF' => 'Afghanistan',
			'AX' => 'Aland Islands',
			'AL' => 'Albania',
			'DZ' => 'Algeria',
			'AS' => 'American Samoa',
			'AD' => 'Andorra',
			'AO' => 'Angola',
			'AI' => 'Anguilla',
			'AQ' => 'Antarctica',
			'AG' => 'Antigua and Barbuda',
			'AR' => 'Argentina',
			'AM' => 'Armenia',
			'AW' => 'Aruba',
			'AU' => 'Australia',
			'AT' => 'Austria',
			'AZ' => 'Azerbaijan',
			'BS' => 'Bahamas',
			'BH' => 'Bahrain',
			'BD' => 'Bangladesh',
			'BB' => 'Barbados',
			'BY' => 'Belarus',
			'BE' => 'Belgium',
			'BZ' => 'Belize',
			'BJ' => 'Benin',
			'BM' => 'Bermuda',
			'BT' => 'Bhutan',
			'BO' => 'Bolivia',
			'BA' => 'Bosnia And Herzegovina',
			'BW' => 'Botswana',
			'BV' => 'Bouvet Island',
			'BR' => 'Brazil',
			'IO' => 'British Indian Ocean Territory',
			'BN' => 'Brunei Darussalam',
			'BG' => 'Bulgaria',
			'BF' => 'Burkina Faso',
			'BI' => 'Burundi',
			'KH' => 'Cambodia',
			'CM' => 'Cameroon',
			'CA' => 'Canada',
			'CV' => 'Cape Verde',
			'KY' => 'Cayman Islands',
			'CF' => 'Central African Republic',
			'TD' => 'Chad',
			'CL' => 'Chile',
			'CN' => 'China',
			'CX' => 'Christmas Island',
			'CC' => 'Cocos (Keeling) Islands',
			'CO' => 'Colombia',
			'KM' => 'Comoros',
			'CG' => 'Congo', 
			'CD' => 'Congo, Democratic Republic',
			'CK' => 'Cook Islands',
			'CR' => 'Costa Rica',
			'CI' => 'Cote D\'Ivoire',
			'HR' => 'Croatia',
			'CU' => 'Cuba',
			'CY' => 'Cyprus',
			'CZ' => 'Czech Republic',
			'DK' => 'Denmark',
			'DJ' => 'Djibouti',
			'DM' => 'Dominica',
			'DO' => 'Dominican Republic',
			'EC' => 'Ecuador',
			'EG' => 'Egypt',
			'SV' => 'El Salvador',
			'GQ' => 'Equatorial Guinea',
			'ER' => 'Eritrea',
			'EE' => 'Estonia',
			'ET' => 'Ethiopia',
			'FK' => 'Falkland Islands (Malvinas)',
			'FO' => 'Faroe Islands',
			'FJ' => 'Fiji',
			'FI' => 'Finland',
			'FR' => 'France',
			'GF' => 'French Guiana',
			'PF' => 'French Polynesia',
			'TF' => 'French Southern Territories',
			'GA' => 'Gabon',
			'GM' => 'Gambia',
			'GE' => 'Georgia',
			'DE' => 'Germany',
			'GH' => 'Ghana',
			'GI' => 'Gibraltar',
			'GR' => 'Greece',
			'GL' => 'Greenland',
			'GD' => 'Grenada',
			'GP' => 'Guadeloupe',
			'GU' => 'Guam',
			'GT' => 'Guatemala',
			'GG' => 'Guernsey',
			'GN' => 'Guinea',
			'GW' => 'Guinea-Bissau',
			'GY' => 'Guyana',
			'HT' => 'Haiti',
			'HM' => 'Heard Island and Mcdonald Islands',
			'VA' => 'Holy See (Vatican City State)',
			'HN' => 'Honduras',
			'HK' => 'Hong Kong',
			'HU' => 'Hungary',
			'IS' => 'Iceland',
			'IN' => 'India',
			'ID' => 'Indonesia',
			'IR' => 'Iran, Islamic Republic of',
			'IQ' => 'Iraq',
			'IE' => 'Ireland',
			'IM' => 'Isle of Man',
			'IL' => 'Israel',
			'IT' => 'Italy',
			'JM' => 'Jamaica',
			'JP' => 'Japan',
			'JE' => 'Jersey',
			'JO' => 'Jordan',
			'KZ' => 'Kazakhstan',
			'KE' => 'Kenya',
			'KI' => 'Kiribati',
			'KR' => 'South Korea',
			'KW' => 'Kuwait',
			'KG' => 'Kyrgyzstan',
			'LA' => 'Lao People\'s Democratic Republic',
			'LV' => 'Latvia',
			'LB' => 'Lebanon',
			'LS' => 'Lesotho',
			'LR' => 'Liberia',
			'LY' => 'Libya',
			'LI' => 'Liechtenstein',
			'LT' => 'Lithuania',
			'LU' => 'Luxembourg',
			'MO' => 'Macao',
			'MK' => 'Macedonia',
			'MG' => 'Madagascar',
			'MW' => 'Malawi',
			'MY' => 'Malaysia',
			'MV' => 'Maldives',
			'ML' => 'Mali',
			'MT' => 'Malta',
			'MH' => 'Marshall Islands',
			'MQ' => 'Martinique',
			'MR' => 'Mauritania',
			'MU' => 'Mauritius',
			'YT' => 'Mayotte',
			'MX' => 'Mexico',
			'FM' => 'Micronesia, Federated States of', 
			'MD' => 'Moldova',
			'MC' => 'Monaco',
			'MN' => 'Mongolia',
			'ME' => 'Montenegro',
			'MS' => 'Montserrat',
			'MA' => 'Morocco',
			'MZ' => 'Mozambique',
			'MM' => 'Myanmar',
			'NA' => 'Namibia',
			'NR' => 'Nauru',
			'NP' => 'Nepal',
			'NL' => 'Netherlands',
			'AN' => 'Netherlands Antilles',
			'NC' => 'New Caledonia',
			'NZ' => 'New Zealand',
			'NI' => 'Nicaragua',
			'NE' => 'Niger',
			'NG' => 'Nigeria',
			'NU' => 'Niue',
			'NF' => 'Norfolk Island',
			'MP' => 'Northern Mariana Islands',
			'NO' => 'Norway',
			'OM' => 'Oman',
			'PK' => 'Pakistan',
			'PW' => 'Palau',
			'PS' => 'Palestinian Territory, Occupied',
			'PA' => 'Panama',
			'PG' => 'Papua New Guinea',
			'PY' => 'Paraguay',
			'PE' => 'Peru',
			'PH' => 'Philippines',
			'PN' => 'Pitcairn',
			'PL' => 'Poland',
			'PT' => 'Portugal',
			'PR' => 'Puerto Rico',
			'QA' => 'Qatar',
			'RE' => 'Reunion',
			'RO' => 'Romania',
			'RU' => 'Russian Federation',
			'RW' => 'Rwanda',
			'BL' => 'Saint Barthelemy',
			'SH' => 'Saint Helena',
			'KN' => 'Saint Kitts and Nevis',
			'LC' => 'Saint Lucia',
			'MF' => 'Saint Martin',
			'PM' => 'Saint Pierre and Miquelon',
			'VC' => 'Saint Vincent and Grenadines',
			'WS' => 'Samoa',
			'SM' => 'San Marino',
			'ST' => 'Sao Tome and Principe',
			'SA' => 'Saudi Arabia',
			'SN' => 'Senegal',
			'RS' => 'Serbia',
			'SC' => 'Seychelles',
			'SL' => 'Sierra Leone',
			'SG' => 'Singapore',
			'SK' => 'Slovakia',
			'SI' => 'Slovenia',
			'SB' => 'Solomon Islands',
			'SO' => 'Somalia',
			'ZA' => 'South Africa',
			'GS' => 'South Georgia and Sandwich Islands',
			'ES' => 'Spain',
			'LK' => 'Sri Lanka',
			'SD' => 'Sudan',
			'SR' => 'Suriname',
			'SJ' => 'Svalbard and Jan Mayen',
			'SZ' => 'Swaziland',
			'SE' => 'Sweden',
			'CH' => 'Switzerland',
			'SY' => 'Syrian Arab Republic',
			'TW' => 'Taiwan',
			'TJ' => 'Tajikistan',
			'TZ' => 'Tanzania',
			'TH' => 'Thailand',
			'TL' => 'Timor-Leste',
			'TG' => 'Togo',
			'TK' => 'Tokelau',
			'TO' => 'Tonga',
			'TT' => 'Trinidad and Tobago',
			'TN' => 'Tunisia',
			'TR' => 'Turkey',
			'TM' => 'Turkmenistan',
			'TC' => 'Turks and Caicos Islands',
			'TV' => 'Tuvalu',
			'UG' => 'Uganda',
			'UA' => 'Ukraine',
			'AE' => 'United Arab Emirates',
			'GB' => 'United Kingdom',
			'US' => 'United States',
			'UM' => 'United States Outlying Islands',
			'UY' => 'Uruguay',
			'UZ' => 'Uzbekistan',
			'VU' => 'Vanuatu',
			'VE' => 'Venezuela',
			'VN' => 'Viet Nam',
			'VG' => 'Virgin Islands, British',
			'VI' => 'Virgin Islands, United States',
			'WF' => 'Wallis and Futuna',
			'EH' => 'Western Sahara',
			'YE' => 'Yemen',
			'ZM' => 'Zambia',
			'ZW' => 'Zimbabwe',
			'EU' => 'Europe',
			
		);
		
		/**
		 * Return a list of 
		 *
		 *			- ISO 2 language codes, respective 
		 *			- ISO 2 country code, with 
		 *			- locale language name
		 *
		 * @note	'bg-BG' => 'Bulgarian'
		 */
		 
		static public function languageCodeCountryCodeLanguageName() { 
			return QInternationalisation_Iso::$iso2language_iso2country_languagename;
		}
		
		/**
		 * ISO 2 language code, mapped to their respective ISO 2 country code and language name
		 *
		 * @note	https://stackoverflow.com/questions/10175658/is-there-a-simple-way-to-get-the-language-code-from-a-country-code-in-php
		 * @note	https://www.loc.gov/standards/iso639-2/php/code_list.php
		 *
		 */
		 
		static private $iso2language_iso2country_languagename = array(
			'af-ZA' => 'Afrikaans',
			'am-ET' => 'Amharic',
			'ar-AE' => 'Arabic',
			'ar-BH' => 'Arabic',
			'ar-DZ' => 'Arabic',
			'ar-EG' => 'Arabic',
			'ar-IQ' => 'Arabic',
			'ar-JO' => 'Arabic',
			'ar-KW' => 'Arabic',
			'ar-LB' => 'Arabic',
			'ar-LY' => 'Arabic',
			'ar-MA' => 'Arabic',
			'ar-OM' => 'Arabic',
			'ar-QA' => 'Arabic',
			'ar-SA' => 'Arabic',
			'ar-SY' => 'Arabic',
			'ar-TN' => 'Arabic',
			'ar-YE' => 'Arabic',
			'as-IN' => 'Assamese',
			'ba-RU' => 'Bashkir',
			'be-BY' => 'Byelorussian',
			'bg-BG' => 'Bulgarian',
			'bn-BD' => 'Bengali',
			'bn-IN' => 'Bengali',
			'bo-CN' => 'Tibetan',
			'br-FR' => 'Breton',
			'ca-ES' => 'Catalan',
			'co-FR' => 'Corsican',
			'cs-CZ' => 'Czech',
			'cy-GB' => 'Welsh',
			'da-DK' => 'Danish',
			'de-AT' => 'German',
			'de-CH' => 'German',
			'de-DE' => 'German',
			'de-LI' => 'German',
			'de-LU' => 'German',
			'dv-MV' => 'Maldivian',
			'el-GR' => 'Greek',
			'en-AU' => 'English',
			'en-BZ' => 'English',
			'en-CA' => 'English',
			'en-GB' => 'English',
			'en-IE' => 'English',
			'en-IN' => 'English',
			'en-JM' => 'English',
			'en-MY' => 'English',
			'en-NZ' => 'English',
			'en-PH' => 'English',
			'en-SG' => 'English',
			'en-TT' => 'English',
			'en-US' => 'English',
			'en-ZA' => 'English',
			'en-ZW' => 'English',
			'es-AR' => 'Spanish',
			'es-BO' => 'Spanish',
			'es-CL' => 'Spanish',
			'es-CO' => 'Spanish',
			'es-CR' => 'Spanish',
			'es-DO' => 'Spanish',
			'es-EC' => 'Spanish',
			'es-ES' => 'Spanish',
			'es-GT' => 'Spanish',
			'es-HN' => 'Spanish',
			'es-MX' => 'Spanish',
			'es-NI' => 'Spanish',
			'es-PA' => 'Spanish',
			'es-PE' => 'Spanish',
			'es-PR' => 'Spanish',
			'es-PY' => 'Spanish',
			'es-SV' => 'Spanish',
			'es-US' => 'Spanish',
			'es-UY' => 'Spanish',
			'es-VE' => 'Spanish',
			'et-EE' => 'Estonian',
			'eu-ES' => 'Basque',
			'fa-IR' => 'Persian',
			'fi-FI' => 'Finnish',
			'fo-FO' => 'Faeroese',
			'fr-BE' => 'French',
			'fr-CA' => 'French',
			'fr-CH' => 'French',
			'fr-FR' => 'French',
			'fr-LU' => 'French',
			'fr-MC' => 'French',
			'fy-NL' => 'Frisian',
			'ga-IE' => 'Irish',
			'gd-GB' => 'Gaelic',
			'gl-ES' => 'Galician',
			'gu-IN' => 'Gujarati',
			'he-IL' => 'Hebrew',
			'hi-IN' => 'Hindi',
			'hr-BA' => 'Croatian',
			'hr-HR' => 'Croatian',
			'hu-HU' => 'Hungarian',
			'hy-AM' => 'Armenian',
			'id-ID' => 'Indonesian',
			'ig-NG' => 'Igbo',
			'ii-CN' => 'Sichuan Yi',
			'is-IS' => 'Icelandic',
			'it-CH' => 'Italian',
			'it-IT' => 'Italian',
			'ja-JP' => 'Japanese',
			'ka-GE' => 'Georgian',
			'kk-KZ' => 'Kazakh',
			'kl-GL' => 'Greenlandic',
			'km-KH' => 'Central Khmer',
			'kn-IN' => 'Kannada',
			'ko-KR' => 'Korean',
			'ky-KG' => 'Kirghiz',
			'lb-LU' => 'Luxembourg',
			'lo-LA' => 'Laothian',
			'lt-LT' => 'Lithuanian',
			'lv-LV' => 'Latvian',
			'mi-NZ' => 'Maori',
			'mk-MK' => 'Macedonian',
			'ml-IN' => 'Malayalam',
			'mn-MN' => 'Mongolian',
			'mr-IN' => 'Marathi',
			'ms-BN' => 'Malay',
			'ms-MY' => 'Malay',
			'mt-MT' => 'Maltese',
			'nb-NO' => 'Norwegian Bokmål',
			'ne-NP' => 'Nepali',
			'nl-BE' => 'Dutch',
			'nl-NL' => 'Dutch',
			'nn-NO' => 'Norwegian Nynorsk',
			'oc-FR' => 'Occitan',
			'or-IN' => 'Oriya',
			'pa-IN' => 'Panjabi',
			'pl-PL' => 'Polish',
			'ps-AF' => 'Pushto',
			'pt-BR' => 'Portuguese',
			'pt-PT' => 'Portuguese',
			'rm-CH' => 'Romansh',
			'ro-RO' => 'Romanian',
			'ru-RU' => 'Russian',
			'rw-RW' => 'Kinyarwanda',
			'sa-IN' => 'Sanskrit',
			'se-FI' => 'Northern Sami',
			'se-NO' => 'Northern Sami',
			'se-SE' => 'Northern Sami',
			'si-LK' => 'Sinhala',
			'sk-SK' => 'Slovak',
			'sl-SI' => 'Slovenian',
			'sq-AL' => 'Albanian',
			'sv-FI' => 'Swedish',
			'sv-SE' => 'Swedish',
			'sw-KE' => 'Swahili',
			'ta-IN' => 'Tamil',
			'te-IN' => 'Telugu',
			'th-TH' => 'Thai',
			'tk-TM' => 'Turkmen',
			'tn-ZA' => 'Tswana',
			'tr-TR' => 'Turkish',
			'tt-RU' => 'Tartar',
			'ug-CN' => 'Uighur',
			'uk-UA' => 'Ukrainian',
			'ur-PK' => 'Urdu',
			'vi-VN' => 'Vietnamese',
			'wo-SN' => 'Wolof',
			'xh-ZA' => 'Xhosa',
			'yo-NG' => 'Yoruba',
			'zh-CN' => 'Chinese',
			'zh-HK' => 'Chinese',
			'zh-MO' => 'Chinese',
			'zh-SG' => 'Chinese',
			'zh-TW' => 'Chinese',
			'zu-ZA' => 'Zulu',
			'en-EU' => 'Europe',
			
		);
		
		/**
		 * Return a list of 
		 *
		 *			- ISO 2 country codes, with their respective 
		 *			- ISO 3 country codes
		 *
		 * @param	$code		string
		 *
		 * @return				mixed
		 *
		 */
		 
		static public function countryCodeCountryCode( string $code = '' ) { 
			if( empty( $code ) ) {
				return QInternationalisation_Iso::$iso2country_iso3country;
			}
			
			return QInternationalisation_Iso::$iso2country_iso3country[$code];
		}
		
		/**
		 * ISO 2 country code, mapped to their respective ISO 3 country code
		 */
		 
		static private $iso2country_iso3country = array(
			'AS' => 'ASM',
			'AD' => 'AND',
			'AE' => 'ARE',
			'AF' => 'AFG',
			'AG' => 'ATG',
			'AI' => 'AIA',
			'AL' => 'ALB',
			'AM' => 'ARM',
			'AQ' => 'ATA',
			'AR' => 'ARG',
			'AT' => 'AUT',
			'AU' => 'AUS',
			'AW' => 'ABW',
			'AZ' => 'AZE',
			'AO' => 'AGO',
			'AX' => 'ALA',
			'BA' => 'BIH',
			'BB' => 'BRB',
			'BD' => 'BGD',
			'BE' => 'BEL',
			'BF' => 'BFA',
			'BG' => 'BGR',
			'BH' => 'BHR',
			'BI' => 'BDI',
			'BJ' => 'BEN',
			'BM' => 'BMU',
			'BN' => 'BRN',
			'BO' => 'BOL',
			'BR' => 'BRA',
			'BS' => 'BHS',
			'BT' => 'BTN',
			'BW' => 'BWA',
			'BY' => 'BLR',
			'BZ' => 'BLZ',
			'CA' => 'CAN',
			'CC' => 'CCK',
			'CF' => 'CAF',
			'CG' => 'COG',
			'CH' => 'CHE',
			'CI' => 'CIV',
			'CK' => 'COK',
			'CL' => 'CHL',
			'CM' => 'CMR',
			'CN' => 'CHN',
			'CO' => 'COL',
			'CR' => 'CRI',
			'CU' => 'CUB',
			'CV' => 'CPV',
			'CW' => 'CUW',
			'CX' => 'CXR',
			'CY' => 'CYP',
			'CZ' => 'CZE',
			'CD' => 'COD',
			'DE' => 'DEU',
			'DJ' => 'DJI',
			'DK' => 'DNK',
			'DM' => 'DMA',
			'DO' => 'DOM',
			'DZ' => 'DZA',
			'EC' => 'ECU',
			'EE' => 'EST',
			'EG' => 'EGY',
			'EH' => 'ESH',
			'ER' => 'ERI',
			'ES' => 'ESP',
			'ET' => 'ETH',
			'EU' => 'EUR',
			'FI' => 'FIN',
			'FJ' => 'FJI',
			'FK' => 'FLK',
			'FO' => 'FRO',
			'FR' => 'FRA',
			'FM' => 'FSM',
			'GA' => 'GAB',
			'GB' => 'GBR',
			'GD' => 'GRD',
			'GE' => 'GEO',
			'GF' => 'GUF',
			'GI' => 'GIB',
			'GL' => 'GRL',
			'GM' => 'GMB',
			'GN' => 'GNB',
			'GP' => 'GLP',
			'GQ' => 'GNQ',
			'GR' => 'GRC',
			'GS' => 'SGS',
			'GT' => 'GTM',
			'GU' => 'GUM',
			'GY' => 'GUY',
			'GH' => 'GHA',
			'HK' => 'HKG',
			'HN' => 'HMD',
			'HR' => 'HRV',
			'HU' => 'HUN',
			'ID' => 'IDN',
			'IL' => 'ISR',
			'IM' => 'IMN',
			'IN' => 'IND',
			'IO' => 'IOT',
			'IR' => 'IRN',
			'IQ' => 'IRQ',
			'IS' => 'ISL',
			'IT' => 'ITA',
			'IE' => 'IRL',
			'JA' => 'JAM',
			'JE' => 'JEY',
			'JO' => 'JOR',
			'JP' => 'JPN',
			'KE' => 'KEN',
			'KG' => 'KGZ',
			'KH' => 'KHM',
			'KI' => 'KIR',
			'KM' => 'COM',
			'KN' => 'KNA',
			'KW' => 'KWT',
			'KY' => 'CYM',
			'KZ' => 'KAZ',
			'KR' => 'KOR',
			'LA' => 'LAO',
			'LC' => 'LCA',
			'LI' => 'LIE',
			'LK' => 'LKA',
			'LR' => 'LBR',
			'LS' => 'LSO',
			'LT' => 'LTU',
			'LU' => 'LUX',
			'LV' => 'LVA',
			'LY' => 'LBV',
			'MA' => 'MAR',
			'MC' => 'MCO',
			'ME' => 'MNE',
			'MF' => 'MAF',
			'MG' => 'MDG',
			'MH' => 'MHL',
			'MK' => 'MKD',
			'ML' => 'MLI',
			'MM' => 'MMR',
			'MN' => 'MNG',
			'MO' => 'MAC',
			'MP' => 'MNP',
			'MQ' => 'MTQ',
			'MR' => 'MRT',
			'MS' => 'MSR',
			'MT' => 'MLT',
			'MU' => 'MUS',
			'MV' => 'MDV',
			'MW' => 'MWI',
			'MX' => 'MEX',
			'MY' => 'MYS',
			'MZ' => 'MOZ',
			'YT' => 'MYT',
			'NA' => 'NAM',
			'NC' => 'NCL',
			'NE' => 'NER',
			'NF' => 'NFK',
			'NG' => 'NGA',
			'NI' => 'NIC',
			'NO' => 'NOR',
			'NP' => 'NPL',
			'NR' => 'NRU',
			'NU' => 'NIU',
			'NZ' => 'NZL',
			'NL' => 'NLD',
			'OM' => 'OMN',
			'PA' => 'PAN',
			'PE' => 'PER',
			'PF' => 'PYF',
			'PG' => 'PNG',
			'PH' => 'PHL',
			'PL' => 'POL',
			'PM' => 'SPM',
			'PN' => 'PCN',
			'PR' => 'PRI',
			'PT' => 'PRT',
			'PW' => 'PLW',
			'PY' => 'PRY',
			'PK' => 'PAK',
			'QA' => 'QAT',
			'RE' => 'REU',
			'RO' => 'ROU',
			'RS' => 'SRB',
			'RU' => 'RUS',
			'RW' => 'RWA',
			'SA' => 'SAU',
			'SB' => 'SLB',
			'SC' => 'SYC',
			'SD' => 'SDN',
			'SE' => 'SWE',
			'SG' => 'SGP',
			'SI' => 'SVN',
			'SJ' => 'SJM',
			'SK' => 'SVK',
			'SL' => 'SLE',
			'SM' => 'SMR',
			'SN' => 'SEN',
			'SO' => 'SOM',
			'SR' => 'SUR',
			'SS' => 'SSD',
			'ST' => 'STP',
			'SV' => 'SLV',
			'SY' => 'SYR',
			'SZ' => 'SWZ',
			'SH' => 'SHN',
			'TC' => 'TCA',
			'TD' => 'TCD',
			'TF' => 'ATF',
			'TG' => 'TGO',
			'TH' => 'THA',
			'TJ' => 'TJK',
			'TK' => 'TKL',
			'TL' => 'TLS',
			'TM' => 'TKM',
			'TO' => 'TON',
			'TR' => 'TUR',
			'TT' => 'TTO',
			'TU' => 'TUN',
			'TV' => 'TUV',
			'TW' => 'TWN',
			'TZ' => 'TZA',
			'UA' => 'UKR',
			'UG' => 'UGA',
			'UM' => 'UMI',
			'US' => 'USA',
			'UY' => 'URY',
			'VA' => 'VAT',
			'VC' => 'VCT',
			'VI' => 'VIR',
			'VN' => 'VNM',
			'VU' => 'VUT',
			'VE' => 'VEN',
			'WF' => 'WLF',
			'WS' => 'WSM',
			'YE' => 'YEM',
			'YT' => 'MYT',
			'ZA' => 'ZAF',
			'ZM' => 'ZMB',
			'ZW' => 'ZWE',
		
		);
		
		/**
		 * Return a list of 
		 *
		 *			- ISO 3 country codes, with their respective 
		 *			- ISO 3 currency codes
		 *
		 * @param	$code		string
		 *
		 * @return				mixed
		 *
		 */
		 
		static public function countryCodeCurrencyCode( string $code = '' ) { 
			if( empty( $code ) ) {
				return QInternationalisation_Iso::$iso3country_iso3currency;
			}
			
			return QInternationalisation_Iso::$iso3country_iso3currency[$code];
		}
		
		/**
		 * Map ISO 3 country codes to their respective ISO 3 currency code
		 *
		 * @note		https://www.nationsonline.org/oneworld/country_code_list.htm
		 * @note		https://www.science.co.il/international/Currency-codes.php
		 *
		 */
		 
		static private $iso3country_iso3currency = array(
			'AND' => 'EUR',
			'ARE' => 'AED',		
			'AFG' => 'AFN',		
			'ATG' => 'XCD',		
			'AIA' => 'XCD',		
			'ALB' => 'ALL',		
			'ARM' => 'AMD',
			'ASM' => 'USD',
			'ATG' => 'XCD',
			'ARG' => 'ARS',
			'AUT' => 'EUR',
			'AUS' => 'AUD',
			'ABW' => 'AWG',		
			'AZE' => 'AZN',
			'AGO' => 'AOA',
			'ALA' => 'EUR',
			'BIH' => 'BAM',
			'BRB' => 'BBD',
			'BGD' => 'BDT',
			'BEL' => 'EUR',
			'BFA' => 'XOF',
			'BGR' => 'BGN',
			'BHR' => 'BHD',
			'BDI' => 'BIF',		
			'BEN' => 'XOF',
			'BMU' => 'BMD',
			'BRN' => 'BND',
			'BOL' => 'BOB',
			'BRA' => 'BRL',
			'BHS' => 'BSD',
			'BTN' => 'BTN',
			'BWA' => 'BWP',
			'BLR' => 'BYR',
			'BLZ' => 'BZD',
			'BLM' => 'EUR',
			'BVT' => 'NOK',
			'CAN' => 'CAD',
			'CCK' => 'AUD',
			'CAF' => 'EUR',		
			'COG' => 'XAF',
			'CHE' => 'CHF',		
			'CIV' => 'XOF',
			'COK' => 'NZD',
			'CHL' => 'CLF',
			'CMR' => 'XAF',
			'CHN' => 'CNY',
			'COL' => 'COP',
			'CRI' => 'CRC',
			'CUB' => 'CUC',
			'CPV' => 'CVE',
			'CUW' => 'ANG',
			'CXR' => 'AUD',
			'CYP' => 'EUR',
			'CZE' => 'CZK',
			'COD' => 'CDF',
			'DEU' => 'EUR',
			'DJI' => 'DJF',
			'DNK' => 'DKK',
			'DMA' => 'XCD',
			'DOM' => 'DOP',
			'DZA' => 'DZD',
			'ECU' => 'USD',
			'EST' => 'EUR',
			'EGY' => 'EGP', 
			'ESH' => 'MAD',		
			'ERI' => 'ERN',
			'ESP' => 'EUR',		
			'ETH' => 'ETB',
			'FIN' => 'EUR',
			'FJI' => 'FJD',
			'FLK' => 'FKP',
			'FRO' => 'DKK',
			'FRA' => 'EUR',
			'FSM' => 'USD',
			'GAB' => 'XAF',
			'GBR' => 'GBP',
			'GRD' => 'XCD',
			'GEO' => 'GEL',
			'GUF' => 'EUR',
			'GIB' => 'GIP',
			'GRL' => 'DKK',
			'GMB' => 'GMD',
			'GNB' => 'XOF',
			'GLP' => 'EUR',
			'GNQ' => 'GNF',		
			'GRC' => 'EUR',
			'SGS' => 'FKP',		
			'GTM' => 'GTQ',
			'GUM' => 'USD',
			'GUY' => 'GYD',
			'GGY' => 'GBP',
			'GHA' => 'GHS',
			'HKG' => 'HKD',
			'HMD' => 'AUD',		
			'HRV' => 'EUR',		
			'HUN' => 'HUF',
			'HND' => 'HNL',
			'HTI' => 'HTG',
			'IDN' => 'IDR',
			'ISR' => 'ILS',
			'IMN' => 'GBP',
			'IND' => 'INR',
			'IOT' => 'USD',	
			'IRQ' => 'IQD',
			'IRN' => 'IRR',
			'ISL' => 'ISK',
			'ITA' => 'EUR',
			'IRL' => 'EUR',
			'JAM' => 'JMD',
			'JEY' => 'GBP',
			'JOR' => 'JOD',
			'JPN' => 'JPY',
			'KEN' => 'KES',
			'KGZ' => 'KGS',
			'KHM' => 'KHR',		
			'KIR' => 'AUD',
			'COM' => 'KMF',		
			'KNA' => 'XCD',		
			'KWT' => 'KWD',
			'CYM' => 'KYD',		
			'KAZ' => 'KZT',
			'KOR' => 'KRW',
			'LAO' => 'LAK',
			'LCA' => 'XCD',		
			'LIE' => 'CHF',
			'LKA' => 'LKR',		
			'LBR' => 'LRD',
			'LSO' => 'ZAR',
			'LTU' => 'EUR',
			'LUX' => 'EUR',
			'LVA' => 'EUR',
			'LBV' => 'LYD',
			'LBN' => 'LBP',
			'MAR' => 'MAD',
			'MCO' => 'EUR',
			'MNE' => 'EUR',
			'MAF' => 'EUR',		
			'MDG' => 'MGA',
			'MHL' => 'USD',
			'MLI' => 'XOF',
			'MMR' => 'MMK',
			'MNG' => 'MNT',
			'MAC' => 'MOP',
			'MKD' => 'MKD',
			'MNP' => 'USD',		
			'MTQ' => 'EUR',
			'MRT' => 'MRO',
			'MSR' => 'XCD',
			'MLT' => 'EUR',
			'MUS' => 'MUR',
			'MDV' => 'MVR',
			'MWI' => 'MWK',
			'MEX' => 'MXN',
			'MYS' => 'MYR',
			'MOZ' => 'MZN',
			'MYT' => 'EUR', 
			'NAM' => 'NAD',
			'NCL' => 'XPF',
			'NER' => 'XOF',
			'NFK' => 'AUD',
			'NGA' => 'NGN',
			'NIC' => 'NIO',
			'NOR' => 'NOK',
			'NPL' => 'NPR',
			'NRU' => 'AUD',
			'NIU' => 'NZD',
			'NZL' => 'NZD',
			'NLD' => 'EUR',
			'OMN' => 'OMR',
			'PAN' => 'PAB',
			'PER' => 'PEN',
			'PRI' => 'USD',
			'PYF' => 'XPF',		
			'PNG' => 'PGK',
			'PHL' => 'PHP',
			'POL' => 'PLN',
			'PAK' => 'PKR',
			'SPM' => 'EUR',
			'PCN' => 'NZD',
			'PRT' => 'EUR',
			'PLW' => 'USD',
			'PRY' => 'PYG',
			'QAT' => 'QAR',
			'REU' => 'EUR',
			'ROU' => 'RON',
			'SRB' => 'RSD',
			'RUS' => 'RUB',
			'RWA' => 'RWF',
			'SAU' => 'SAR',
			'SLB' => 'SBD',
			'SYC' => 'SCR',
			'SDN' => 'SDG',
			'SWE' => 'SEK',
			'SGP' => 'SGD',
			'SVN' => 'EUR',
			'SJM' => 'NOK',
			'SVK' => 'EUR',
			'SLE' => 'SLL',
			'SMR' => 'EUR',
			'SEN' => 'XOF',
			'SOM' => 'SOS',
			'SUR' => 'SRD',
			'SSD' => 'SSP',
			'STP' => 'STD',
			'SLV' => 'SVC',		
			'SYR' => 'SYP',
			'SWZ' => 'SZL',
			'SHN' => 'SHP',
			'TCA' => 'USD',
			'TCD' => 'XAF',		
			'ATF' => 'EUR',		
			'TGO' => 'XOF',
			'THA' => 'THB',
			'TJK' => 'TJS',
			'TKL' => 'NZD',
			'TLS' => 'USD',
			'TKM' => 'TMT',
			'TON' => 'TOP',
			'TUR' => 'TRY',
			'TTO' => 'TTD',
			'TUN' => 'TND',
			'TUV' => 'AUD',
			'TWN' => 'TWD',
			'TZA' => 'TZS',
			'UKR' => 'UAH',
			'UGA' => 'UGX',
			'UMI' => 'USD',
			'USA' => 'USD',
			'URY' => 'UYU',
			'UZB' => 'UZS',
			'VAT' => 'EUR',
			'VCT' => 'XCD',	
			'VIR' => 'USD',
			'VNM' => 'VND',
			'VUT' => 'VUV',
			'VEN' => 'VEF',
			'WLF' => 'XPF',
			'WSM' => 'WST',		
			'YEM' => 'YER',
			'MYT' => 'EUR',
			'ZAF' => 'ZAR',		
			'ZMB' => 'ZMW',
			'ZWE' => 'ZWL',
			'EUR' => 'EUR',
			
		);
		
		/**
		 * Return a list of 
		 *
		 *			- ISO 3 country codes, with their respective 
		 *			- HTML entity for currency symbol
		 *
		 * @param	$code		string
		 *
		 * @return				mixed
		 *
		 */
		 
		static public function countryCodeCurrencySymbol( string $code = '' ) { 
			if( empty( $code ) ) {
				return QInternationalisation_Iso::$iso2country_currencysymbol;
			}
			
			return QInternationalisation_Iso::$iso2country_currencysymbol[$code];
		}
		
		/**
		 * ISO 3 country code, mapped to respective currency symbol
		 *
		 * @see		https://gist.github.com/Gibbs/3920259
		 * @see		https://www.w3schools.com/charsets/ref_utf_currency.asp
		 * @see		https://graphemica.com/
		 *
		 */
		 
		static private $iso2country_currencysymbol = array(
			'AND' => '&#128;',
			'ARE' => '&#1583;.&#1573;',		
			'AFG' => '&#1547;',		
			'ATG' => '&#164;',		
			'AIA' => '&#164;',		
			'ALB' => '&#128;',		
			'ARM' => '&#1423;',
			'ASM' => '&#36;',
			'ARG' => '&#36;',
			'AUT' => '&#128;',
			'AUS' => '&#36;',
			'ABW' => '&#402;',		
			'AZE' => '&#1084;&#1072;&#1085;',
			'AGO' => '&#75;&#122;', 
			'ALA' => '&#128;',
			'BIH' => '&#75;&#77;',
			'BRB' => '&#36;',
			'BGD' => '&#2547;',
			'BEL' => '&#128;',
			'BFA' => '&#164;',
			'BGR' => '&#1083;&#1074;',
			'BHR' => '.&#1583;.&#1576;',
			'BDI' => '&#70;&#66;&#117;',		
			'BEN' => '&#164;',
			'BMU' => '&#36;',
			'BRN' => '&#36;',
			'BOL' => '&#36;&#98;',
			'BRA' => '&#82;&#36;',
			'BHS' => '&#36;',
			'BTN' => '&#78;&#117;&#46;',
			'BWA' => '&#80;',
			'BLR' => '&#112;&#46;',
			'BLZ' => '&#66;&#90;&#36;',
			'BVT' => '&#107;&#114;',
			'BLM' => '&#128;',
			'CAN' => '&#36;',
			'CCK' => '&#36;',
			'CAF' => '&#128;',		
			'COG' => '&#164;',
			'CHE' => '&#8355;',		
			'CIV' => '&#164;',
			'COK' => '&#36;',
			'CHL' => '&#85;&#70;',
			'CMR' => '&#164;',
			'CHN' => '&#165;',
			'COL' => '&#36;',
			'CRI' => '&#8353;',
			'CUB' => 'CUC&#36;',
			'CPV' => '&#36;',
			'CUW' => '&#402;',
			'CXR' => '&#36;',
			'CYP' => '&#128;',
			'CZE' => '&#75;&#269;',
			'COD' => '&#70;&#67;',
			'DEU' => '&#128;',
			'DJI' => '&#70;&#100;&#106;',
			'DNK' => '&#75;&#114;&#46;',
			'DMA' => '&#164;',
			'DOM' => '&#82;&#68;&#36;',
			'DZA' => '&#1583;&#1580;',
			'ECU' => '&#36;',
			'EST' => '&#128;',
			'EGY' => '&#163;',
			'ESH' => '&#1583;.&#1605;.',		
			'ERI' => '&#78;&#102;&#107;',
			'ESP' => '&#128;',		
			'ETH' => '&#66;&#114;',
			'FIN' => '&#128;',
			'FJI' => '&#36;',
			'FLK' => '&#163;',
			'FRO' => '&#75;&#114;&#46;',
			'FRA' => '&#128;',
			'FSM' => '&#36;', 
			'GAB' => '&#164;',
			'GBR' => '&#163;',
			'GRD' => '&#164;',
			'GEO' => '&#4314;',
			'GUF' => '&#128;',
			'GIB' => '&#163;',
			'GRL' => '&#75;&#114;&#46;',
			'GMB' => '&#68;',
			'GNB' => '&#164;',
			'GLP' => '&#128;',
			'GNQ' => '&#70;&#71;',		
			'GRC' => '&#128;',
			'GHA' => '&#8373;',
			'GGY' => '&#163;',
			'SGS' => '&#70;&#71;',		
			'GTM' => '&#81;',
			'GUM' => '&#36;',
			'GUY' => '&#36;',
			'HKG' => '&#36;',
			'HMD' => '&#36;',		
			'HRV' => '&#128;',		
			'HUN' => '&#70;&#116;',
			'HND' => '&#76;',
			'HTI' => '&#71;',
			'IDN' => '&#82;&#112;',
			'ISR' => '&#8362;',
			'IMN' => '&#163;',
			'IND' => '&#x20B9;',
			'IOT' => '&#36;',	
			'IRQ' => '&#1593;.&#1583;',
			'IRN' => '&#65020;',
			'ISL' => '&#107;&#114;',
			'ITA' => '&#128;',
			'IRL' => '&#128;',
			'JAM' => '&#74;&#36;',
			'JEY' => '&#163;',
			'JOR' => '&#74;&#68;',
			'JPN' => '&#165;',
			'KEN' => '&#75;&#83;&#104;',
			'KGZ' => '&#1083;&#1074;',
			'KHM' => '&#6107;',		
			'KIR' => '&#36;',
			'COM' => '&#67;&#70;',		
			'KNA' => '&#164;',		
			'KOR' => '&#1583;.&#1603;',
			'KWT' => '&#1583;.&#1603;',
			'CYM' => '&#1583;.&#1603;',		
			'KAZ' => '&#1083;&#1074;',
			'LAO' => '&#8365;',
			'LCA' => '&#164;',		
			'LIE' => '&#8355;',
			'LKA' => '&#8360;',		
			'LBR' => '&#36;',
			'LSO' => '&#82;',
			'LTU' => '&#128;',
			'LUX' => '&#128;',
			'LVA' => '&#128;',
			'LBV' => '&#1604;.&#1583;',
			'LBN' => '&#1604;',
			'MAR' => '&#1583;.&#1605;.',
			'MCO' => '&#128;',
			'MNE' => '&#128;',
			'MAF' => '&#128;',		
			'MDG' => '&#65;&#114;',
			'MHL' => '&#36;',
			'MLI' => '&#164;',
			'MMR' => '&#75;',
			'MNG' => '&#8366;',
			'MAC' => '&#77;&#79;&#80;&#36;',
			'MKD' => '&#1076;&#1077;&#1085;',
			'MNP' => '&#36;',		
			'MTQ' => '&#128;',
			'MRT' => '&#85;&#77;',
			'MSR' => '&#164;',
			'MLT' => '&#128;',
			'MUS' => '&#8360;',
			'MDV' => '.&#1923;',
			'MWI' => '&#77;&#75;',
			'MEX' => '&#8369;',
			'MYS' => '&#82;&#109;',
			'MOZ' => '&#77;&#84;',
			'NAM' => '&#36;',
			'MYT' => '&#128;',
			'NCL' => '&#164;',
			'NER' => '&#164;',
			'NFK' => '&#36;',
			'NGA' => '&#8358;',
			'NIC' => '&#67;&#36;',
			'NOR' => '&#107;&#114;',
			'NPL' => '&#8360;',
			'NRU' => '&#36;',
			'NIU' => '&#36;',
			'NZL' => '&#36;',
			'NLD' => '&#128;',
			'OMN' => '&#65020;',
			'PAN' => '&#66;&#47;&#46;',
			'PER' => '&#83;&#47;&#46;',
			'PRI' => '&#36;',
			'PYF' => '&#164;',		
			'PNG' => '&#75;',
			'PHL' => '&#8369;',
			'POL' => '&#122;&#322;',
			'PAK' => '&#65020;',
			'SPM' => '&#128;',
			'PCN' => '&#36;',
			'PRT' => '&#128;',
			'PLW' => '&#36;',
			'PRY' => '&#71;&#115;',
			'QAT' => '&#65020;',
			'REU' => '&#128;',
			'ROU' => '&#108;&#101;&#105;',
			'SRB' => '&#1044;&#1080;&#1085;&#46;',
			'RUS' => '&#1412;',
			'RWA' => '&#1585;.&#1587;',
			'SAU' => '&#65020;',
			'SLB' => '&#36;',
			'SYC' => '&#8360;',
			'SDN' => '&#163;',
			'SWE' => '&#107;&#114;',
			'SGP' => '&#36;',
			'SVN' => '&#128;',
			'SJM' => '&#107;&#114;',
			'SVK' => '&#128;',
			'SLE' => '&#76;&#101;',
			'SMR' => '&#128;',
			'SEN' => '&#164;',
			'SOM' => '&#83;',
			'SUR' => '&#36;',
			'SSD' => '&#163;',
			'STP' => '&#68;&#98;',
			'SLV' => '&#36;',		
			'SYR' => '&#163;',
			'SWZ' => '&#76;',
			'SHN' => '&#163;', 
			'TCA' => '&#36;',
			'TCD' => '&#164;',		
			'ATF' => '&#128;',		
			'TGO' => '&#164;',
			'THA' => '&#3647;',
			'TJK' => '&#84;&#74;&#83;',
			'TKL' => '&#36;',
			'TLS' => '&#36;',
			'TKM' => '&#109;',
			'TON' => '&#84;&#36;',
			'TUR' => '&#8378;',
			'TTO' => '&#36;',
			'TUN' => '&#1583;.&#1578;',
			'TUV' => '&#36;',
			'TWN' => '&#36;',
			'TZA' => '&#163;', 
			'UKR' => '&#8372;',
			'UGA' => '&#85;&#83;&#104;',
			'UMI' => '&#36;',
			'USA' => '&#36;',
			'URY' => '&#36;&#85;',
			'UZB' => '&#1083;&#1074;',
			'VAT' => '&#128;',
			'VCT' => '&#164;',	
			'VIR' => '&#36;',
			'VNM' => '&#8363;',
			'VUT' => '&#86;&#84;',
			'VEN' => '&#66;&#115;',
			'WLF' => '&#164;',
			'WSM' => '&#87;&#83;&#36;',		
			'YEM' => '&#65020;',
			'MYT' => '&#128;',
			'ZAF' => '&#82;',		
			'ZMB' => '&#90;&#75;',
			'ZWE' => '&#90;&#36;',
			'EUR' => '&#128;',
			
		);
		
		
		// https://countrywisecodes.com/world-currency-codes
		// http://fasteri.com/list/3/three-letter-country-codes
	}
	
?>